TaskMent/urls.py
from django.urls import path
from.forms import *
from . import views
app_name='tmg'

urlpatterns = [
    
    path('',views.dashbord,name='dash'),
    path('AllTasks/' ,views.AllTasks,name='AllTasks'),

    path('tasks/' ,views.tasks,name='tasks'),
    path('addtask/',views.AddTask,name='addtask'),
    path('taskupdate/<str:pk>',views.TaskUpdate,name='taskupdate'),
    path('delete/<str:pk>',views.deletetask,name='deletetask'),
    
    path('dep/',views.AllDepartment,name='alldep'),
    path('adddep/',views.AddDepartment,name='adddep'),
    path('DepUpdate/<str:pk>',views.DepUpdate,name='DepUpdate'),
    path('Depdelete/<str:pk>',views.Depdelete,name='Depdelete'),
    
    path('Sections/',views.AllSections,name='Setions'),
    path('addsection/',views.AddSetions,name='addsection'),
    path('secupdate/<str:pk>',views.UpdateSections,name='secupdate'),
    path('Secdelete/<str:pk>',views.DeleteSection,name='Secdelete'),
    
    path('AllTaskOwner/',views.AllTaskOwner,name='AllTaskOwner'),
    path('addto/',views.AddTaskOwner,name='addto'),
    path('toupdate/<str:pk>',views.UpdateTaskOwner,name='toupdate'),
    path('todelete/<str:pk>',views.DeleteTaskOwner,name='todelete'),
    path('AllTaskSituation/',views.AllTaskSituation,name='AllTaskSituation'),
    path('TaskSituation/',views.AddTaskSituation,name='TaskSituation'),
    path('UpdateTaskSituation/<str:pk>',views.UpdateTaskSituation,name='UpdateTaskSituation'),
    path('TaskSituationdelete/<str:pk>',views.DeleteTaskSituation,name='TaskSituationdelete'),
    path('AllMonitoringTool/',views.AllMonitoringTool,name='AllMonitoringTool'),
    path('addMonitoringTool/',views.AddMonitoringTool,name='addMonitoringTool'),
    path('UpdateMonitoringTool/<str:pk>',views.UpdateMonitoringTool,name='UpdateMonitoringTool'),
    path('MonitoringTooldelete/<str:pk>',views.DeleteMonitoringTool,name='MonitoringTooldelete'),
    
    path('AllFollowUpFrequency/',views.AllFollowUpFrequency,name='AllFollowUpFrequency'),
    path('AddFollowUpFrequency/',views.AddFollowUpFrequency,name='AddFollowUpFrequency'),
    path('UpdateFollowUpFrequency/<str:pk>',views.UpdateFollowUpFrequency,name='UpdateFollowUpFrequency'),
    path('DeletFollowUpFrequency/<str:pk>',views.DeletFollowUpFrequency,name='DeletFollowUpFrequency'),
    # path('<slug:slug>/' ,views.tasks_slug,name='tasks_slug'),

]

acc/urls.py
from django.urls import path
from . import views 


# Create your views here.
app_name='acc'
urlpatterns = [    
        path('' ,views.User_login,name='ulogin'),            
        path('logout/' ,views.userLogout,name='logout'),
        path('signup/',views.SignUp,name='signup'),
        path('UserProfile/',views.UserProfile,name='UserProfile'),        
        # path('<slug:slug/',views.tasks_slug,name='tsk_slug'),        

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
    path('tmg/', include('TaskMent.urls',namespace='tmg')),
    path('', include('acc.urls',namespace='acc')),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TaskMent/forms.py
from django.forms import widgets
from django.forms.widgets import DateTimeInput
from acc import models
from django import forms
from django.contrib.auth.models import  User
from .models import *
from django.contrib.auth.forms import  UserCreationForm
from django.utils import timezone

class AddTasks(forms.ModelForm):        
    class Meta:
        model = Tasks
        fields=[
                        
            # 'user',
            'DepName',
            'sec',
                'TaskOwner',
                'TaskSituation',
                'MonitoringTool',
                'FOF',
                'Status',
                'Task',
                'TaskDate',
                'DueDate',
                'Comment'
                ]
        widgets={
            # 'user':forms.Select(attrs={'class':'form-control'}),
       
            'DepName':forms.Select(attrs={'class':'form-control'}),
            'sec':forms.Select(attrs={'class':'form-control'}),

            'TaskOwner':forms.Select(attrs={'class':'form-control' }),
            'TaskSituation':forms.Select(attrs={'class':'form-control'}),
            'MonitoringTool':forms.Select(attrs={'class':'form-control'}),
            
            'FOF':forms.Select(attrs={'class':'form-control'}),
            'Status':forms.Select(attrs={'class':'form-control'}),
            'Task':forms.TextInput(attrs={'class':'form-control'}),
            
            'TaskDate':forms.DateInput(format = '%Y-%m-%d',attrs={'type': 'date'}),
            'DueDate':forms.DateInput(format = '%Y-%m-%d',attrs={'type': 'date'}),
            'Comment':forms.Textarea(attrs={'class':'form-control'})
        }
class AddTDep(forms.ModelForm):
    class Meta:
        model = Department
        fields=['DepName']
        widgets={
            'DepName':forms.TextInput(attrs={'class':'form-control'}),
        }

class AddSectionsForm(forms.ModelForm) :    
    class Meta:
        model = Section
        fields = ['section','Dep']       
        widgets={
            'DepName':forms.TextInput(attrs={'class':'form-control'}),
            'Section':forms.TextInput(attrs={'class':'form-control'})
        }
class AddTaskOwnerForm(forms.ModelForm) :    
    class Meta:
        model = TaskOwner
        fields = ['TOName']       
        widgets={
            'TOName':forms.TextInput(attrs={'class':'form-control'}),
            
        }        
class AddTaskSituationForm(forms.ModelForm) :    
    class Meta:
        model = TaskSituation
        fields = ['SituationName']       
        widgets={
            'SituationName':forms.TextInput(attrs={'class':'form-control'}),
            
        }                
        
class AddMonitoringToolForm(forms.ModelForm) :    
    class Meta:
        model = MonitoringTool
        fields = ['SourceName']       
        widgets={
            'SourceName':forms.TextInput(attrs={'class':'form-control'}),
            
        }                
        
class AddFollowUpFrequencyForm(forms.ModelForm) :    
    class Meta:
        model = FollowUpFrequency
        fields = ['FUFName']       
        widgets={
            'FUFName':forms.TextInput(attrs={'class':'form-control'}),
            
        }                        

TaskMent/views.py
from django.contrib.auth import authenticate
from django.http import request
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from .models import Department, Tasks
from .forms import *
from .filters import *
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from .decorators import *
# from acc.models import *

@login_required()
@allowedgroup(allweduser=['admin'])
def AllTasks (request):     
    gettsk=Tasks.objects.all()
    Open=Tasks.objects.filter(Status='Open').count()
    compete=Tasks.objects.filter(Status='Complete').count()
    Struggling=Tasks.objects.filter(Status='Struggling').count()
    In_Progress=Tasks.objects.filter(Status='In_Progress').count() 
    searchfilter=TaskFilter(request.GET,queryset=gettsk)
    gettsk=searchfilter.qs
    
    
    context={
        'gettsk':gettsk,
        'GetAllTasks':AddTasks(),
        'Struggling':Struggling,
        'Open':Open,
        'compete':compete,
        'In_Progress':In_Progress,
        'myTaskFilter':searchfilter,
        
        }           
    return render(request,'tasks/tasks.html',context)

# Create your views here.
@login_required()
def tasks (request):     
    gettsk=Tasks.objects.filter(user=request.user) 
    Open=Tasks.objects.filter(Status='Open').count()
    compete=Tasks.objects.filter(Status='Complete').count()
    Struggling=Tasks.objects.filter(Status='Struggling').count()
    In_Progress=Tasks.objects.filter(Status='In_Progress').count() 
    searchfilter=TaskFilter(request.GET,queryset=gettsk)
    gettsk=searchfilter.qs
    
    
    context={
        'gettsk':gettsk,
        'GetAllTasks':AddTasks(),
        'Struggling':Struggling,
        'Open':Open,
        'compete':compete,
        'In_Progress':In_Progress,
        'myTaskFilter':searchfilter,
        
        }           
    return render(request,'tasks/tasks.html',context)

@login_required()
@allowedgroup(allweduser=['admin'])
def dashbord(request):
    user=User.objects.count()
    tsk=Tasks.objects.all()
    tskcount=Tasks.objects.count()
    Open=Tasks.objects.filter(Status='Open').count()
    compete=Tasks.objects.filter(Status='Complete').count()
    Struggling=Tasks.objects.filter(Status='Struggling').count()
    In_Progress=Tasks.objects.filter(Status='In_Progress').count()


    context={
        'userCount':user,
        'tsk':tsk,
        'tskcount':tskcount,
        'Struggling':Struggling,
        'Open':Open,
        'compete':compete,
        'In_Progress':In_Progress
    }
    return render(request,'index.html',{'context':context})
@login_required()
def AddTask(request):
          
    if request.method=='POST': 
             
            addtask=AddTasks(request.POST)              
            if addtask.is_valid():               
                           
              instance=addtask.save(commit=False) 
              instance.user=request.user
              instance.save()              
            return redirect('tmg:tasks')      
        
    context={
        
        'form':AddTasks()
    }
    return render(request ,'tasks/addtasks.html',context)
@login_required()
def TaskUpdate(request,pk):
    task=Tasks.objects.get(id=pk)
    form=AddTasks(instance=task)
    if request.method=="POST":
        form=AddTasks(request.POST,instance=task)
        if form.is_valid():
            ## here the add
            form.user = request.user
            form.save()
        return redirect('tmg:tasks')      
    context={
        'form':form
    }
    return render(request ,'tasks/TaskUpdate.html',context) 
@login_required()   
def deletetask(request,pk):
    task=Tasks.objects.get(id=pk)
    if request.method=="POST":
        task.delete()
        return redirect('tmg:tasks')
        
    context={
        'form':task
    }
    return render(request ,'tasks/taskdelete.html',context)  
@login_required() 
# end Tasks Operation   
@login_required()  
@allowedgroup(allweduser=['admin'])  
def AllDepartment (request):     
    getdep=Department.objects.all()
    contDep=Department.objects.count()
    context={
        'getdep':getdep,
         'contDep':contDep,
        }           
    return render(request,'tasks/Department.html',context)
@login_required()     
@allowedgroup(allweduser=['admin'])   
def AddDepartment(request):  
    
    if request.method=='POST':        
            adddep=AddTDep(request.POST)  
            if adddep.is_valid():
               adddep.save()
            return redirect('tmg:alldep')       
    context={
        
        'form':AddTDep()
    }
    return render(request ,'tasks/addDep.html',context)   
@login_required()
@allowedgroup(allweduser=['admin']) 
def DepUpdate(request,pk):
    dep=Department.objects.get(id=pk)
    form=AddTDep(instance=dep)
    if request.method=="POST":
        form=AddTDep(request.POST,instance=dep)
        if form.is_valid():
            form.save()
        return redirect('tmg:alldep')    
    
    context={"form":form}
    return render(request,'tasks/depupdate.html',context)     
@login_required()
@allowedgroup(allweduser=['admin'])  
def Depdelete(request,pk):
    dep=Department.objects.get(id=pk)
    if request.method=="POST":
        dep.delete()
        return redirect('tmg:alldep')
    context={
        'form':dep
    }    
    return render(request,'tasks/depdelete.html',context)   
# end of Department Function
@login_required()
@allowedgroup(allweduser=['admin'])
def AllSections(request):
    getAllSections=Section.objects.all()       
    contSection=Section.objects.count()
    context={
        'getSections':getAllSections,
        'contSection':contSection
    }
    return render(request,'tasks/AllSections.html',context)
@login_required()
@allowedgroup(allweduser=['admin']) 
def AddSetions(request):    
    if request.method=='POST':             
            form=AddSectionsForm(request.POST)  
            if form.is_valid():
               form.save()
            return redirect('tmg:Setions')       
    context={
        
        'form':AddSectionsForm()
    }    
    return render(request,'tasks/AddSetions.html',context)
@login_required()
@allowedgroup(allweduser=['admin']) 
def UpdateSections(request,pk):    
    section=Section.objects.get(id=pk)
    form=AddSectionsForm(instance=section)
    if request.method=="POST":
        form=AddSectionsForm(request.POST,instance=section)
        if form.is_valid():
            form.save()
            return redirect('tmg:Setions')
        else:
            form=AddSectionsForm() 
    context={
        
        'form':form
    }              
    return render (request,'tasks/sectionsupdate.html',context)
@login_required()
@allowedgroup(allweduser=['admin']) 
def DeleteSection(request,pk):
    form=Section.objects.get(id=pk)
    if request.method=="POST":
        form.delete()
        return redirect('tmg:Setions')   
    context={
        'form':form
    }
    return render(request,'tasks/sectiondelete.html',context)
# end of Sections
@login_required()
@allowedgroup(allweduser=['admin']) 
def AllTaskOwner(request):
    getAllSections=TaskOwner.objects.all()       
    contSection=TaskOwner.objects.count()
    context={
        'getSections':getAllSections,
        'contSection':contSection
    }
    return render(request,'tasks/AllTaskOwner.html',context)
@login_required()
@allowedgroup(allweduser=['admin'])
def AddTaskOwner(request):    
    if request.method=='POST':             
            form=AddTaskOwnerForm(request.POST)  
            if form.is_valid():
               form.save()
            return redirect('tmg:AllTaskOwner')       
    context={
        
        'form':AddTaskOwnerForm()
    }    
    return render(request,'tasks/AddTaskowner.html',context)
@login_required()
@allowedgroup(allweduser=['admin']) 
def UpdateTaskOwner(request,pk):    
    section=TaskOwner.objects.get(id=pk)
    form=AddTaskOwnerForm(instance=section)
    if request.method=="POST":
        form=AddTaskOwnerForm(request.POST,instance=section)
        if form.is_valid():
            form.save()
            return redirect('tmg:AllTaskOwner')
        else:
            form=AddTaskOwnerForm() 
    context={
        
        'form':form
    }              
    return render (request,'tasks/TaskOwnerUpdate.html',context)
@login_required()
@allowedgroup(allweduser=['admin']) 
def DeleteTaskOwner(request,pk):
    form=TaskOwner.objects.get(id=pk)
    if request.method=="POST":
        form.delete()
        return redirect('tmg:AllTaskOwner')   
    context={
        'form':form
    }
    return render(request,'tasks/TaskOwnerDelete.html',context)
# end of TaskOwner
@login_required()
@allowedgroup(allweduser=['admin']) 
def AllTaskSituation(request):
    getAllSections=TaskSituation.objects.all()       
    contSection=TaskSituation.objects.count()
    context={
        'getSections':getAllSections,
        'contSection':contSection
    }
    return render(request,'tasks/AllTaskSituationr.html',context)
@login_required()
@allowedgroup(allweduser=['admin']) 
def AddTaskSituation(request):    
    if request.method=='POST':             
            form=AddTaskSituationForm(request.POST)  
            if form.is_valid():
               form.save()
            return redirect('tmg:AllTaskSituation')       
    context={
        
        'form':AddTaskSituationForm()
    }    
    return render(request,'tasks/AddTaskSituation.html',context)
@login_required()
@allowedgroup(allweduser=['admin'])
def UpdateTaskSituation(request,pk):    
    section=TaskSituation.objects.get(id=pk)
    form=AddTaskSituationForm(instance=section)
    if request.method=="POST":
        form=AddTaskSituationForm(request.POST,instance=section)
        if form.is_valid():
            form.save()
            return redirect('tmg:AllTaskSituation')
        else:
            form=AddTaskSituationForm() 
    context={
        
        'form':form
    }              

TaskMent/templates/tasks/AddFollowUpFrequency.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="container">

    <form method="POST">
        {% csrf_token %} {{form}}
</div>

<button type="submit" class="btn btn-primary">Submit</button>

</div>
</form>
</div>

</div>

{% endblock content %}

TaskMent/templates/tasks/AllSections.html
{% extends 'base.html' %} {% load static %} {% block content %}


<div class="container">
    <div class="signup pt-5 pl-5">
        <!-- Animated -->
        <div class="animated fadeIn">
            <!-- Widgets  -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="stat-widget-five">
                                <div class="stat-icon dib flat-color-4">
                                    <i class="pe-7s-users"></i>
                                </div>
                                <div class="stat-content">
                                    <div class="text-left dib">
                                        <div class="stat-text"><span class="count">{{contSection}}</span></div>
                                        <div class="stat-heading">Sections</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="table pl-2 pr-3 pt-2">
                    <a href="{% url 'tmg:addsection' %}" class="btn btn-success">Add Sections </a>
                    <div class="card-body--">
                        <div class="table-stats order-table ov-h">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>

                                        <th scope="col">Section Name </th>
                                        <th scope="col">Department's List</th>

                                        <th scope="col">Functions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for x in getSections %}
                                    <tr>

                                        <td>{{x.id}}</td>
                                        <td>{{x.section}}</td>
                                        <td>{{x.Dep}}</td>
                                        <td>
                                            <a href="{% url 'tmg:secupdate' x.id %}" class="badge badge-pill badge-info">Update </a>
                                            <a href="{% url 'tmg:Secdelete' x.id %}" class="badge badge-pill badge-danger">Delete </a>

                                        </td>





                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            {% endblock content %}

TaskMent/templates/tasks/AllTaskSituationr.html
{% extends 'base.html' %} {% load static %} {% block content %}


<div class="container">
    <div class="signup pt-5 pl-5">
        <!-- Animated -->
        <div class="animated fadeIn">
            <!-- Widgets  -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="stat-widget-five">
                                <div class="stat-icon dib flat-color-4">
                                    <i class="pe-7s-users"></i>
                                </div>
                                <div class="stat-content">
                                    <div class="text-left dib">
                                        <div class="stat-text"><span class="count">{{contSection}}</span></div>
                                        <div class="stat-heading">Task Situation</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="table pl-2 pr-3 pt-2">
                    <a href="{% url 'tmg:TaskSituation' %}" class="btn btn-success">Add TaskSituationr </a>
                    <div class="card-body--">
                        <div class="table-stats order-table ov-h">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>

                                        <th scope="col">Situation Name </th>

                                        <th scope="col">Functions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for x in getSections %}
                                    <tr>

                                        <td>{{x.id}}</td>
                                        <td>{{x.SituationName}}</td>

                                        <td>
                                            <a href="{% url 'tmg:UpdateTaskSituation' x.id %}" class="badge badge-pill badge-info">Update </a>
                                            <a href="{% url 'tmg:TaskSituationdelete' x.id %}" class="badge badge-pill badge-danger">Delete </a>

                                        </td>





                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            {% endblock content %}

TaskMent/templates/tasks/AllTasks.html
{% extends 'base.html' %} {% load static %} {% comment %} {% load crispy_forms_tags %} {% endcomment %} {% block content %}

<div class="container">

    <div class="signup pt-5 pl-5">

        <!-- Animated -->
        <div class="animated fadeIn">

            <!-- Widgets  -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="stat-widget-five">
                                <div class="stat-icon dib flat-color-1">
                                    <i class="pe-7s-cash"></i>
                                </div>

                                <div class="stat-content">
                                    <div class="text-left dib">
                                        <div class="stat-text"><span class="count">{{Open}}</span></div>
                                        <div class="stat-heading">Open</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="stat-widget-five">
                                <div class="stat-icon dib flat-color-2">
                                    <i class="pe-7s-cart"></i>
                                </div>
                                <div class="stat-content">
                                    <div class="text-left dib">
                                        <div class="stat-text"><span class="count">{{Struggling}}</span></div>
                                        <div class="stat-heading">Struggling</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="stat-widget-five">
                                <div class="stat-icon dib flat-color-3">
                                    <i class="pe-7s-browser"></i>
                                </div>
                                <div class="stat-content">
                                    <div class="text-left dib">
                                        <div class="stat-text"><span class="count">{{compete}}</span></div>
                                        <div class="stat-heading">compete</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="stat-widget-five">
                                <div class="stat-icon dib flat-color-4">
                                    <i class="pe-7s-users"></i>
                                </div>
                                <div class="stat-content">
                                    <div class="text-left dib">
                                        <div class="stat-text"><span class="count">{{In_Progress}}</span></div>
                                        <div class="stat-heading">In_Progress</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /Widgets -->
            <!--  Traffic  -->


        </div>

    </div>


    <div class="col-12 col-md-3 col-xl-2 bd-sidebar ">
        <form class=" bd-search d-flex align-items-center ">
            <span class="algolia-autocomplete" style="position: relative; display: inline-block; direction: ltr;">
                <div class="container-fluid bg-3 text-right " >    
                   
                        <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3 " >
                            <div class="col w3-col l3 m3 s12" >
                              <div class="p-8 border border-primary  "style="padding: 15px 20px; margin:10px 20px "> {{myTaskFilter.form}} 
                              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button></button>
                            </div>
                            </div>
                        </form>
                        </div>
                   
    </div>
   
    <div class="table pl-2 pr-3 pt-2 table table-striped">

        <a href="{% url 'tmg:addtask' %}" class="btn btn-success">Add Task </a>
        <div class="card-body--">
            <div class="table-stats order-table ov-h">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">user</th>
                            <th scope="col">Status</th>

                            <th scope="col">Department</th>
                            <th scope="col">FollowUpFrequency</th>
                            <th scope="col">TaskOwner</th>
                            <th scope="col">MonitoringTool</th>
                            <th scope="col">DueDate</th>
                            <th scope="col">TaskDate</th>

                            <th scope="col">Functions</th>


                        </tr>
                    </thead>
                    <tbody>
                        {% for x in gettsk %}
                        <tr>
                            <td>{{x.user}}</td>
                            <td>
                                <span class="badge badge-pill badge-info">{{x.Status}}</span>
            </td>
            <td>{{x.DepName}}</td>
            <td>{{x.FOF}}</td>
            <td>{{x.TaskOwner}}</td>


            <td>{{x.MonitoringTool}}</td>
            <td>{{x.TaskDate}}</td>
            <td>{{x.DueDate}}</td>



            <td>
                <a href="{% url 'tmg:taskupdate' x.id %}" class="badge badge-pill badge-info">Update </a>
                <a href="{% url 'tmg:deletetask' x.id %}" class="badge badge-pill badge-danger">Delete </a>

            </td>





            </tr>
            {% endfor %}
            </tbody>
            </table>
    </div>
</div>
</div>

{% comment %} end container {% endcomment %}
</div>

{% endblock content %}

TaskMent/templates/tasks/FollowUpFrequencyDelete.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">

    <form method="POST">
        {% csrf_token %}
        <div class="card" style="width: 40rem;">

            <div class="card-body">
                <h5 class="card-title "></h5>
                {% comment %}
                <p class="card-text text text-danger">Sure, you want to delete that object?</p> {% endcomment %}
                <div class="alert alert-danger" role="alert">
                    Sure, you want to delete that object?
                </div>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Follow Up Frequency : {{form.FUFName}}</li>

            </ul>

            <div class="card-body">
                <a href="{ % url 'tmg:DeletFollowUpFrequency' form.id % }" class="card-link"><button type="submit" class="btn btn-danger">Delete</button></a>
                <a href="{% url 'tmg:AllFollowUpFrequency' %}" class="card-link btn btn-info">Back </a>

            </div>
        </div>
    </form>

</div>
{% endblock content %}

TaskMent/templates/tasks/MonitoringTooldelete.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">

    <form method="POST">
        {% csrf_token %}
        <div class="card" style="width: 40rem;">

            <div class="card-body">
                <h5 class="card-title "></h5>
                {% comment %}
                <p class="card-text text text-danger">Sure, you want to delete that object?</p> {% endcomment %}
                <div class="alert alert-danger" role="alert">
                    Sure, you want to delete that object?
                </div>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">MonitoringTool : {{form.SourceName}}</li>

            </ul>

            <div class="card-body">
                <a href="{ % url 'tmg:MonitoringTooldelete' form.id % }" class="card-link"><button type="submit" class="btn btn-danger">Delete</button></a>
                <a href="{% url 'tmg:AllMonitoringTool' %}" class="card-link btn btn-info">Back </a>

            </div>
        </div>
    </form>

</div>
{% endblock content %}