TaskMent/urls.py
from django.urls import path
from.forms import *
from . import views
app_name='tmg'

urlpatterns = [
    
    path('',views.dashbord,name='dash'),
    path('AllTasks/' ,views.AllTasks,name='AllTasks'),

    path('tasks/' ,views.tasks,name='tasks'),
    path('addtask/',views.AddTask,name='addtask'),
    path('taskupdate/<str:pk>',views.TaskUpdate,name='taskupdate'),
    path('delete/<str:pk>',views.deletetask,name='deletetask'),
    
    path('dep/',views.AllDepartment,name='alldep'),
    path('adddep/',views.AddDepartment,name='adddep'),
    path('DepUpdate/<str:pk>',views.DepUpdate,name='DepUpdate'),
    path('Depdelete/<str:pk>',views.Depdelete,name='Depdelete'),
    
    path('Sections/',views.AllSections,name='Setions'),
    path('addsection/',views.AddSetions,name='addsection'),
    path('secupdate/<str:pk>',views.UpdateSections,name='secupdate'),
    path('Secdelete/<str:pk>',views.DeleteSection,name='Secdelete'),
    
    path('AllTaskOwner/',views.AllTaskOwner,name='AllTaskOwner'),
    path('addto/',views.AddTaskOwner,name='addto'),
    path('toupdate/<str:pk>',views.UpdateTaskOwner,name='toupdate'),
    path('todelete/<str:pk>',views.DeleteTaskOwner,name='todelete'),
    path('AllTaskSituation/',views.AllTaskSituation,name='AllTaskSituation'),
    path('TaskSituation/',views.AddTaskSituation,name='TaskSituation'),
    path('UpdateTaskSituation/<str:pk>',views.UpdateTaskSituation,name='UpdateTaskSituation'),
    path('TaskSituationdelete/<str:pk>',views.DeleteTaskSituation,name='TaskSituationdelete'),
    path('AllMonitoringTool/',views.AllMonitoringTool,name='AllMonitoringTool'),
    path('addMonitoringTool/',views.AddMonitoringTool,name='addMonitoringTool'),
    path('UpdateMonitoringTool/<str:pk>',views.UpdateMonitoringTool,name='UpdateMonitoringTool'),
    path('MonitoringTooldelete/<str:pk>',views.DeleteMonitoringTool,name='MonitoringTooldelete'),
    
    path('AllFollowUpFrequency/',views.AllFollowUpFrequency,name='AllFollowUpFrequency'),
    path('AddFollowUpFrequency/',views.AddFollowUpFrequency,name='AddFollowUpFrequency'),
    path('UpdateFollowUpFrequency/<str:pk>',views.UpdateFollowUpFrequency,name='UpdateFollowUpFrequency'),
    path('DeletFollowUpFrequency/<str:pk>',views.DeletFollowUpFrequency,name='DeletFollowUpFrequency'),
    # path('<slug:slug>/' ,views.tasks_slug,name='tasks_slug'),

]

acc/urls.py
from django.urls import path
from . import views 


# Create your views here.
app_name='acc'
urlpatterns = [    
        path('' ,views.User_login,name='ulogin'),            
        path('logout/' ,views.userLogout,name='logout'),
        path('signup/',views.SignUp,name='signup'),
        path('UserProfile/',views.UserProfile,name='UserProfile'),        
        # path('<slug:slug/',views.tasks_slug,name='tsk_slug'),        

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
    path('tmg/', include('TaskMent.urls',namespace='tmg')),
    path('', include('acc.urls',namespace='acc')),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/parts/base.html
{% load static %}
<!DOCTYPE html>
<!--[if gt IE 8]><!-->
<html class="no-js" lang="">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Task-Managment</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'css/cs-skin-elastic.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
    <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />

    <style>
        #weatherWidget .currentDesc {
            color: #ffffff!important;
        }
        
        .traffic-chart {
            min-height: 335px;
        }
        
        #flotPie1 {
            height: 150px;
        }
        
        #flotPie1 td {
            padding: 3px;
        }
        
        #flotPie1 table {
            top: 20px!important;
            right: -10px!important;
        }
        
        .chart-container {
            display: table;
            min-width: 270px;
            text-align: left;
            padding-top: 10px;
            padding-bottom: 10px;
        }
        
        #flotLine5 {
            height: 105px;
        }
        
        #flotBarChart {
            height: 150px;
        }
        
        #cellPaiChart {
            height: 160px;
        }
    </style>
</head>

<body>


    {% block contents %} {% endblock contents %} {% include 'parts/footer.html' %}


</body>

</html>




<script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>

<!--  Chart js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.3/dist/Chart.bundle.min.js"></script>

<!--Chartist Chart-->
<script src="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartist-plugin-legend@0.6.2/chartist-plugin-legend.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/jquery.flot@0.8.3/jquery.flot.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flot-pie@1.0.0/src/jquery.flot.pie.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flot-spline@0.0.1/js/jquery.flot.spline.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/simpleweather@3.1.0/jquery.simpleWeather.min.js"></script>
<script src="{% static 'js/init/weather-init.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/moment.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.js"></script>
<script src="{% static 'js/init/fullcalendar-init.js' %'}"></script>

<!--Local Stuff-->
<script>
    jQuery(document).ready(function($) {
        "use strict";

        // Pie chart flotPie1
        var piedata = [{
            label: "Desktop visits",
            data: [
                [1, 32]
            ],
            color: '#5c6bc0'
        }, {
            label: "Tab visits",
            data: [
                [1, 33]
            ],
            color: '#ef5350'
        }, {
            label: "Mobile visits",
            data: [
                [1, 35]
            ],
            color: '#66bb6a'
        }];

        $.plot('#flotPie1', piedata, {
            series: {
                pie: {
                    show: true,
                    radius: 1,
                    innerRadius: 0.65,
                    label: {
                        show: true,
                        radius: 2 / 3,
                        threshold: 1
                    },
                    stroke: {
                        width: 0
                    }
                }
            },
            grid: {
                hoverable: true,
                clickable: true
            }
        });
        // Pie chart flotPie1  End
        // cellPaiChart
        var cellPaiChart = [{
            label: "Direct Sell",
            data: [
                [1, 65]
            ],
            color: '#5b83de'
        }, {
            label: "Channel Sell",
            data: [
                [1, 35]
            ],
            color: '#00bfa5'
        }];
        $.plot('#cellPaiChart', cellPaiChart, {
            series: {
                pie: {
                    show: true,
                    stroke: {
                        width: 0
                    }
                }
            },
            legend: {
                show: false
            },
            grid: {
                hoverable: true,
                clickable: true
            }

        });
        // cellPaiChart End
        // Line Chart  #flotLine5
        var newCust = [
            [0, 3],
            [1, 5],
            [2, 4],
            [3, 7],
            [4, 9],
            [5, 3],
            [6, 6],
            [7, 4],
            [8, 10]
        ];

        var plot = $.plot($('#flotLine5'), [{
            data: newCust,
            label: 'New Data Flow',
            color: '#fff'
        }], {
            series: {
                lines: {
                    show: true,
                    lineColor: '#fff',
                    lineWidth: 2
                },
                points: {
                    show: true,
                    fill: true,
                    fillColor: "#ffffff",
                    symbol: "circle",
                    radius: 3
                },
                shadowSize: 0
            },
            points: {
                show: true,
            },
            legend: {
                show: false
            },
            grid: {
                show: false
            }
        });
        // Line Chart  #flotLine5 End
        // Traffic Chart using chartist
        if ($('#traffic-chart').length) {
            var chart = new Chartist.Line('#traffic-chart', {
                labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
                series: [
                    [0, 18000, 35000, 25000, 22000, 0],
                    [0, 33000, 15000, 20000, 15000, 300],
                    [0, 15000, 28000, 15000, 30000, 5000]
                ]
            }, {
                low: 0,
                showArea: true,
                showLine: false,
                showPoint: false,
                fullWidth: true,
                axisX: {
                    showGrid: true
                }
            });

            chart.on('draw', function(data) {
                if (data.type === 'line' || data.type === 'area') {
                    data.element.animate({
                        d: {
                            begin: 2000 * data.index,
                            dur: 2000,
                            from: data.path.clone().scale(1, 0).translate(0, data.chartRect.height()).stringify(),
                            to: data.path.clone().stringify(),
                            easing: Chartist.Svg.Easing.easeOutQuint
                        }
                    });
                }
            });
        }
        // Traffic Chart using chartist End
        //Traffic chart chart-js
        if ($('#TrafficChart').length) {
            var ctx = document.getElementById("TrafficChart");
            ctx.height = 150;
            var myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
                    datasets: [{
                        label: "Visit",
                        borderColor: "rgba(4, 73, 203,.09)",
                        borderWidth: "1",
                        backgroundColor: "rgba(4, 73, 203,.5)",
                        data: [0, 2900, 5000, 3300, 6000, 3250, 0]
                    }, {
                        label: "Bounce",
                        borderColor: "rgba(245, 23, 66, 0.9)",
                        borderWidth: "1",
                        backgroundColor: "rgba(245, 23, 66,.5)",
                        pointHighlightStroke: "rgba(245, 23, 66,.5)",
                        data: [0, 4200, 4500, 1600, 4200, 1500, 4000]
                    }, {
                        label: "Targeted",
                        borderColor: "rgba(40, 169, 46, 0.9)",
                        borderWidth: "1",
                        backgroundColor: "rgba(40, 169, 46, .5)",
                        pointHighlightStroke: "rgba(40, 169, 46,.5)",
                        data: [1000, 5200, 3600, 2600, 4200, 5300, 0]
                    }]
                },
                options: {
                    responsive: true,
                    tooltips: {
                        mode: 'index',
                        intersect: false
                    },
                    hover: {
                        mode: 'nearest',
                        intersect: true
                    }

                }
            });
        }
        //Traffic chart chart-js  End
        // Bar Chart #flotBarChart
        $.plot("#flotBarChart", [{
            data: [
                [0, 18],
                [2, 8],
                [4, 5],
                [6, 13],
                [8, 5],
                [10, 7],
                [12, 4],
                [14, 6],
                [16, 15],
                [18, 9],
                [20, 17],
                [22, 7],
                [24, 4],
                [26, 9],
                [28, 11]
            ],
            bars: {
                show: true,
                lineWidth: 0,
                fillColor: '#ffffff8a'
            }
        }], {
            grid: {
                show: false
            }
        });
        // Bar Chart #flotBarChart End
    });
</script>


</body>

</html>

templates/parts/footer.html
 <!-- Footer -->
        <footer class="site-footer">
            <div class="footer-inner bg-white">
                <div class="row">
                    <div class="col-sm-6">
                        Copyright &copy; 2021 IT-Team
                    </div>
                    <div class="col-sm-6 text-right">
                        Designed by <a href="#">It-Team Assema & Darelmona</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- /.site-footer -->
        

templates/parts/leftpanel.html
{% load static %} {% block content %}

<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">
        <div id="main-menu" class="main-menu collapse navbar-collapse">

            <ul class="nav navbar-nav">
                <li class="active">

                    <a href="{% url 'tmg:dash'%}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                </li>
                <li class="menu-title">Task Management</li>
                <!-- /.menu-title -->
                <li class="menu-item-has-children dropdown">
                    <a href="{% url 'tmg:tasks'%}" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-cogs"></i>Tasks</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-puzzle-piece"></i><a href="{% url 'tmg:AllTasks'%}">All Tasks</a></li>

                        <li><i class="fa fa-puzzle-piece"></i><a href="{% url 'tmg:tasks'%}">Tasks</a></li>

                        <li><i class="fa fa-puzzle-piece"></i><a href="{% url 'tmg:alldep'%}">Departments</a></li>
                        <li><i class="fa fa-puzzle-piece"></i><a href="{% url 'tmg:Setions'%}">Sections</a></li>
                        <li><i class="fa fa-puzzle-piece"></i><a href="{% url 'tmg:AllTaskOwner'%}">Task Owner</a></li>
                        <li><i class="fa fa-puzzle-piece"></i><a href="{% url 'tmg:AllTaskSituation'%}">Task Situation</a></li>
                        <li><i class="fa fa-puzzle-piece"></i><a href="{% url 'tmg:AllMonitoringTool'%}">Monitoring Tool</a></li>
                        <li><i class="fa fa-puzzle-piece"></i><a href="{% url 'tmg:AllFollowUpFrequency'%}">Follow Up Frequency</a></li>

                    </ul>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-table"></i>Tables</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-table"></i><a href="tables-basic.html">Basic Table</a></li>
                        <li><i class="fa fa-table"></i><a href="tables-data.html">Data Table</a></li>
                    </ul>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-th"></i>Forms</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-th"></i><a href="forms-basic.html">Basic Form</a></li>
                        <li><i class="menu-icon fa fa-th"></i><a href="forms-advanced.html">Advanced Form</a></li>
                    </ul>
                </li>

                <li class="menu-title">Icons</li>
                <!-- /.menu-title -->

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-tasks"></i>Icons</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-fort-awesome"></i><a href="font-fontawesome.html">Font Awesome</a></li>
                        <li><i class="menu-icon ti-themify-logo"></i><a href="font-themify.html">Themefy Icons</a></li>
                    </ul>
                </li>
                <li>
                    <a href="widgets.html"> <i class="menu-icon ti-email"></i>Widgets </a>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-bar-chart"></i>Charts</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-line-chart"></i><a href="charts-chartjs.html">Chart JS</a></li>
                        <li><i class="menu-icon fa fa-area-chart"></i><a href="charts-flot.html">Flot Chart</a></li>
                        <li><i class="menu-icon fa fa-pie-chart"></i><a href="charts-peity.html">Peity Chart</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-area-chart"></i>Maps</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-map-o"></i><a href="maps-gmap.html">Google Maps</a></li>
                        <li><i class="menu-icon fa fa-street-view"></i><a href="maps-vector.html">Vector Maps</a></li>
                    </ul>
                </li>
                <li class="menu-title">Extras</li>
                <!-- /.menu-title -->

                {% if request.user.group == 'admin' %}
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-glass"></i>Pages</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-sign-in"></i><a href="{% url 'acc:ulogin'%}">Login</a></li>
                        <li><i class="menu-icon fa fa-sign-in"></i><a href="{% url 'acc:signup' %}">Register</a></li>
                        <li><i class="menu-icon fa fa-paper-plane"></i><a href="{% url 'acc:UserProfile'%}"> Profile</a></li>
                        <li><i class="menu-icon fa fa-sign-out"></i><a href="{% url 'acc:logout' %}">LogOut</a></li>

                    </ul>
                </li>
                {% else %}
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-glass"></i>Pages</a>
                    <ul class="sub-menu children dropdown-menu">

                        <li><i class="menu-icon fa fa-sign-out"></i><a href="{% url 'acc:logout' %}">LogOut</a></li>

                    </ul>
                </li>
                {% endif %}


            </ul>

        </div>
        <!-- /.navbar-collapse -->
    </nav>
</aside>

{% endblock content %}

templates/parts/rightpanel.html
{% load static %} {% block content %}

<header>
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        <header id="header" class="header">
            <div class="top-left">
                <div class="navbar-header">
                    <a class="navbar-brand" href="./"><img src="{% static 'images/1.png' %}" alt="Logo"></a>
                    <a class="navbar-brand hidden" href="./"><img src="{% static  'images/1.png' % }" alt="Logo"></a>
                    <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
                </div>
            </div>
            <div class="top-right">
                <div class="header-menu">
                    <div class="header-left">
                        <button class="search-trigger"><i class="fa fa-search"></i></button>
                        <div class="form-inline">
                            <form class="search-form">
                                <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                                <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                            </form>
                        </div>

                        <div class="dropdown for-notification">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-bell"></i>
                                <span class="count bg-danger">3</span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="notification">
                                <p class="red">You have 3 Notification</p>
                                <a class="dropdown-item media" href="#">
                                    <i class="fa fa-check"></i>
                                    <p>Server #1 overloaded.</p>
                                </a>
                                <a class="dropdown-item media" href="#">
                                    <i class="fa fa-info"></i>
                                    <p>Server #2 overloaded.</p>
                                </a>
                                <a class="dropdown-item media" href="#">
                                    <i class="fa fa-warning"></i>
                                    <p>Server #3 overloaded.</p>
                                </a>
                            </div>
                        </div>

                        <div class="dropdown for-message">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="message" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-envelope"></i>
                                <span class="count bg-primary">4</span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="message">
                                <p class="red">You have 4 Mails</p>
                                <a class="dropdown-item media" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="{% static 'avatar/1' %}"></span>
                                    <div class="message media-body">
                                        <span class="name float-left">Jonathan Smith</span>
                                        <span class="time float-right">Just now</span>
                                        <p>Hello, this is an example msg</p>
                                    </div>
                                </a>
                                <a class="dropdown-item media" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="{% static 'avatar/2' %}"></span>
                                    <div class="message media-body">
                                        <span class="name float-left">Jack Sanders</span>
                                        <span class="time float-right">5 minutes ago</span>
                                        <p>Lorem ipsum dolor sit amet, consectetur</p>
                                    </div>
                                </a>
                                <a class="dropdown-item media" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="{% static 'avatar/3' %}"></span>
                                    <div class="message media-body">
                                        <span class="name float-left">Cheryl Wheeler</span>
                                        <span class="time float-right">10 minutes ago</span>
                                        <p>Hello, this is an example msg</p>
                                    </div>
                                </a>
                                <a class="dropdown-item media" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="{% static 'avatar/4' %}"></span>
                                    <div class="message media-body">
                                        <span class="name float-left">Rachel Santos</span>
                                        <span class="time float-right">15 minutes ago</span>
                                        <p>Lorem ipsum dolor sit amet, consectetur</p>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="user-area dropdown float-right">

                        <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="name float-left">{{request.user}}</span> {% comment %} {% for user.profile.image in imgg %} {% if imgg.image %}

                            <!-- <img class="user-avatar rounded-circle" src="{{imgg.image.url}}" alt="User"> {% else %}
                            <img class="user-avatar rounded-circle" src="{% static 'images/admin.jpg' %}" alt="User"> {% endif %} -->
                        </a>
                        {% endfor %} {% endcomment %}
                        <div class="user-menu dropdown-menu">
                            <!-- {% comment %} <a class="nav-link" href="{% url 'acc:UserProfile'%}"><i class="fa fa- user"></i>My Profile</a> {% endcomment %} -->

                            <a class="nav-link" href="#"><i class="fa fa- user"></i>Notifications <span class="count">13</span></a>

                            <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a>

                            <a class="nav-link" href="{% url 'acc:logout' %}"><i class="fa fa-power -off"></i>Logout</a>
                        </div>
                    </div>

                </div>
            </div>
        </header>

        {% endblock content %}